import type { Product } from '../schemas'

/**
 * Demo catalogue.
 *
 * Prices, costs, inventory and specifications are fabricated for the prototype
 * and are NOT a representation of real retail pricing or current product
 * configurations. `costPrice` is server-only and never leaves the merchant-side
 * policy engine.
 *
 * The spread is deliberate: for each of the three demo prompts a different
 * merchant should win on the deterministic scorer.
 */

type Seed = Omit<Product, 'imageUrl' | 'source' | 'currency'> & { imageUrl?: string }

/**
 * Real product photography, served from `public/products/`.
 *
 * Anything not listed here falls back to the generated placeholder at
 * `/product-image/<sku>.svg`, so the catalogue never renders a broken image.
 * To add a photo: drop the file in `public/products/` and add one line.
 */
const PRODUCT_IMAGES: Record<string, string> = {
  'SHP-TUF-A15': '/products/sherpa-tuf-a15.webp',
  'SHP-LOQ-15': '/products/sherpa-loq-15.webp',
  'SHP-VIVO-16': '/products/sherpa-vivo-16.jpg',
  'SHP-NITRO-V16': '/products/sherpa-nitro-v16.jpg',
}

/**
 * Storefront hero artwork, keyed by the SKU it is featured alongside.
 *
 * These are stylised brand illustrations, not photographs of the named unit: a
 * generic laptop wrapped in a liquid ribbon, rendered once per merchant hue
 * (220 / 178 / 340) so the three storefronts read as three different shops
 * built on one system. The catalogue tiles below carry the real product
 * imagery; this slot carries the mood.
 *
 * Illustrations rather than product renders is a deliberate call. The
 * catalogue names real hardware, and generating photorealistic shots of real
 * branded machines would mean shipping synthetic photographs of another
 * manufacturer's product. An obvious illustration cannot be mistaken for one.
 *
 * Transparent background is required: the hero sits on the page's own coloured
 * wash and on a WebGL ribbon, so a baked background would show as a box. A
 * merchant with no entry here still gets a hero, using the shared object
 * render as its subject. See the storefront page.
 */
export const HERO_IMAGES: Record<string, string> = {
  'SHP-TUF-A15': '/products/hero-sherpa.png',
  'CHA-LEGION-PRO-5': '/products/hero-challenger.png',
}

export function heroImageForSku(sku: string): string | null {
  return HERO_IMAGES[sku] ?? null
}

const p = (s: Seed): Product => ({
  currency: 'SGD',
  source: 'seed',
  imageUrl: PRODUCT_IMAGES[s.sku] ?? `/product-image/${s.sku}.svg`,
  ...s,
})

export const SEED_PRODUCTS: Product[] = [
  /* ───────────────  Sherpa Computers — SME, inventory turnover  ─────────────── */
  p({
    id: 'sherpa-tuf-a15',
    merchantId: 'sherpa-computers',
    sku: 'SHP-TUF-A15',
    brand: 'ASUS',
    model: 'TUF Gaming A15',
    title: 'ASUS TUF Gaming A15 (Ryzen 7 / RTX 4060)',
    description:
      'Chunky but well-cooled 15.6" gaming chassis. Strong sustained performance for the price, heavier than a campus-carry machine.',
    price: 1529,
    costPrice: 1330,
    specs: {
      cpu: 'AMD Ryzen 7 7435HS',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 16,
      storageGb: 1000,
      weightKg: 2.2,
      batteryWh: 90,
      generation: 2025,
      screenSize: 15.6,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'cad', 'student', 'last_gen'],
    warrantyYears: 1,
    stock: 6,
    condition: 'new',
  }),
  p({
    id: 'sherpa-loq-15',
    merchantId: 'sherpa-computers',
    sku: 'SHP-LOQ-15',
    brand: 'Lenovo',
    model: 'LOQ 15',
    title: 'Lenovo LOQ 15 (Core i5 / RTX 4050)',
    description: 'Entry gaming value pick. Previous-generation platform, small battery, plenty of stock.',
    price: 1399,
    costPrice: 1215,
    specs: {
      cpu: 'Intel Core i5-13450HX',
      gpu: 'NVIDIA GeForce RTX 4050 6GB',
      ramGb: 16,
      storageGb: 512,
      weightKg: 2.4,
      batteryWh: 60,
      generation: 2024,
      screenSize: 15.6,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'value', 'last_gen', 'overstock'],
    warrantyYears: 1,
    stock: 9,
    condition: 'new',
  }),
  p({
    id: 'sherpa-vivo-16',
    merchantId: 'sherpa-computers',
    sku: 'SHP-VIVO-16',
    brand: 'ASUS',
    model: 'Vivobook Pro 16',
    title: 'ASUS Vivobook Pro 16 (Ryzen 5 / RTX 3050)',
    description: 'Creator-oriented 16" panel with a modest discrete GPU. Lighter than the gaming chassis.',
    price: 1249,
    costPrice: 1090,
    specs: {
      cpu: 'AMD Ryzen 5 7535HS',
      gpu: 'NVIDIA GeForce RTX 3050 6GB',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.9,
      batteryWh: 70,
      generation: 2024,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['creator', 'value', 'last_gen'],
    warrantyYears: 1,
    stock: 5,
    condition: 'new',
  }),
  p({
    id: 'sherpa-tp-e14',
    merchantId: 'sherpa-computers',
    sku: 'SHP-TP-E14',
    brand: 'Lenovo',
    model: 'ThinkPad E14 Gen 6',
    title: 'Lenovo ThinkPad E14 Gen 6 (Core Ultra 5)',
    description: 'Light business 14". Integrated graphics only — fine for code and documents, not for 3D.',
    price: 1189,
    costPrice: 1020,
    specs: {
      cpu: 'Intel Core Ultra 5 125U',
      gpu: 'Intel Graphics (integrated)',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.41,
      batteryWh: 57,
      generation: 2025,
      screenSize: 14,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: false,
    },
    tags: ['business', 'portable', 'dev'],
    warrantyYears: 1,
    stock: 7,
    condition: 'new',
  }),
  p({
    id: 'sherpa-nitro-v16',
    merchantId: 'sherpa-computers',
    sku: 'SHP-NITRO-V16',
    brand: 'Acer',
    model: 'Nitro V16',
    title: 'Acer Nitro V16 (Ryzen 7 / RTX 4060)',
    description: 'Strong price/performance — currently sold out, kept in catalogue to prove inventory filtering.',
    price: 1479,
    costPrice: 1300,
    specs: {
      cpu: 'AMD Ryzen 7 8845HS',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 16,
      storageGb: 1000,
      weightKg: 2.1,
      batteryWh: 76,
      generation: 2025,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'cad', 'value'],
    warrantyYears: 1,
    stock: 0,
    condition: 'new',
  }),
  p({
    id: 'sherpa-ideapad-5r',
    merchantId: 'sherpa-computers',
    sku: 'SHP-IDEAPAD-5R',
    brand: 'Lenovo',
    model: 'IdeaPad Slim 5 (Refurbished)',
    title: 'Lenovo IdeaPad Slim 5 — certified refurbished',
    description: 'Cheapest way into 16 GB. Refurbished stock, integrated graphics, previous generation.',
    price: 949,
    costPrice: 790,
    specs: {
      cpu: 'AMD Ryzen 5 7530U',
      gpu: 'AMD Radeon 660M (integrated)',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.65,
      batteryWh: 56,
      generation: 2023,
      screenSize: 14,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: false,
    },
    tags: ['budget', 'refurbished', 'last_gen', 'overstock'],
    warrantyYears: 1,
    stock: 4,
    condition: 'refurbished',
  }),

  /* ───────────────────  Bizgram — mid-size, margin  ─────────────────── */
  p({
    id: 'biz-legion-5',
    merchantId: 'bizgram',
    sku: 'BIZ-LEGION-5',
    brand: 'Lenovo',
    model: 'Legion 5 16',
    title: 'Lenovo Legion 5 16 (Ryzen 7 / RTX 4060 / 32 GB)',
    description:
      'Current-generation 16" with 32 GB as standard. Handles CAD assemblies and games without thermal drama.',
    price: 1589,
    costPrice: 1325,
    specs: {
      cpu: 'AMD Ryzen 7 8845HS',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 2.35,
      batteryWh: 80,
      generation: 2026,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'cad', 'high_margin'],
    warrantyYears: 2,
    stock: 5,
    condition: 'new',
  }),
  p({
    id: 'biz-zeph-g14',
    merchantId: 'bizgram',
    sku: 'BIZ-ZEPH-G14',
    brand: 'ASUS',
    model: 'ROG Zephyrus G14',
    title: 'ASUS ROG Zephyrus G14 (Ryzen 9 / RTX 4060 / 32 GB)',
    description: 'Discrete graphics in a 1.5 kg chassis. The portability premium is real and so is the price.',
    price: 1899,
    costPrice: 1590,
    specs: {
      cpu: 'AMD Ryzen 9 8945HS',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 1.5,
      batteryWh: 73,
      generation: 2026,
      screenSize: 14,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: false,
    },
    tags: ['portable', 'gaming', 'cad', 'premium', 'high_margin'],
    warrantyYears: 2,
    stock: 3,
    condition: 'new',
  }),
  p({
    id: 'biz-thinkbook-14',
    merchantId: 'bizgram',
    sku: 'BIZ-THINKBOOK-14',
    brand: 'Lenovo',
    model: 'ThinkBook 14 G7',
    title: 'Lenovo ThinkBook 14 G7 (Core Ultra 7 / 32 GB)',
    description: 'Developer machine: 32 GB, 75 Wh pack, 1.38 kg. No discrete GPU, so 3D and gaming are out.',
    price: 1349,
    costPrice: 1130,
    specs: {
      cpu: 'Intel Core Ultra 7 155H',
      gpu: 'Intel Arc Graphics (integrated)',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 1.38,
      batteryWh: 75,
      generation: 2026,
      screenSize: 14,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: false,
    },
    tags: ['business', 'portable', 'battery', 'dev', 'high_margin'],
    warrantyYears: 2,
    stock: 8,
    condition: 'new',
  }),
  p({
    id: 'biz-inspiron-16',
    merchantId: 'bizgram',
    sku: 'BIZ-INSPIRON-16',
    brand: 'Dell',
    model: 'Inspiron 16 Plus',
    title: 'Dell Inspiron 16 Plus (Core Ultra 7 / RTX 4060)',
    description: 'Large battery, discrete GPU, 2.0 kg. A reasonable middle between workstation and gaming chassis.',
    price: 1549,
    costPrice: 1300,
    specs: {
      cpu: 'Intel Core Ultra 7 155H',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 16,
      storageGb: 1000,
      weightKg: 2.0,
      batteryWh: 86,
      generation: 2026,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['creator', 'cad', 'gaming'],
    warrantyYears: 2,
    stock: 4,
    condition: 'new',
  }),
  p({
    id: 'biz-precision-3591',
    merchantId: 'bizgram',
    sku: 'BIZ-PRECISION-3591',
    brand: 'Dell',
    model: 'Precision 3591',
    title: 'Dell Precision 3591 (Core Ultra 7 / RTX A1000 / 32 GB)',
    description:
      'ISV-oriented mobile workstation. Professional-class GPU with CUDA, 32 GB, 1.87 kg. Weaker for gaming than a consumer RTX.',
    price: 1679,
    costPrice: 1420,
    specs: {
      cpu: 'Intel Core Ultra 7 165H',
      gpu: 'NVIDIA RTX A1000 6GB',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 1.87,
      batteryWh: 64,
      generation: 2026,
      screenSize: 15.6,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['workstation', 'cad', 'ml', 'certified'],
    warrantyYears: 2,
    stock: 2,
    condition: 'new',
  }),
  p({
    id: 'biz-swift-14',
    merchantId: 'bizgram',
    sku: 'BIZ-SWIFT-14',
    brand: 'Acer',
    model: 'Swift Go 14',
    title: 'Acer Swift Go 14 (Core Ultra 5 / 16 GB)',
    description: 'Cheap, light and quiet. Integrated graphics; fine for coding and travel, not for CAD.',
    price: 1099,
    costPrice: 910,
    specs: {
      cpu: 'Intel Core Ultra 5 125H',
      gpu: 'Intel Arc Graphics (integrated)',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.32,
      batteryWh: 65,
      generation: 2025,
      screenSize: 14,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: false,
    },
    tags: ['portable', 'battery', 'budget', 'dev'],
    warrantyYears: 2,
    stock: 6,
    condition: 'new',
  }),

  /* ──────────────────  Challenger — chain, AOV / service  ────────────────── */
  p({
    id: 'cha-nitro-v16',
    merchantId: 'challenger',
    sku: 'CHA-NITRO-V16',
    brand: 'Acer',
    model: 'Nitro V16',
    title: 'Acer Nitro V16 (Ryzen 7 / RTX 4060)',
    description: 'Same silicon as the sold-out unit elsewhere, sold with next-day delivery and chain-wide service.',
    price: 1599,
    costPrice: 1320,
    specs: {
      cpu: 'AMD Ryzen 7 8845HS',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ramGb: 16,
      storageGb: 1000,
      weightKg: 2.1,
      batteryWh: 76,
      generation: 2026,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'cad', 'service_attach'],
    warrantyYears: 2,
    stock: 6,
    condition: 'new',
  }),
  p({
    id: 'cha-legion-pro-5',
    merchantId: 'challenger',
    sku: 'CHA-LEGION-PRO-5',
    brand: 'Lenovo',
    model: 'Legion Pro 5 16',
    title: 'Lenovo Legion Pro 5 16 (Core i7 / RTX 4070 / 32 GB)',
    description: 'Top of the demo catalogue. 3-year on-site warranty, and a price that fails most student budgets.',
    price: 2199,
    costPrice: 1850,
    specs: {
      cpu: 'Intel Core i7-14700HX',
      gpu: 'NVIDIA GeForce RTX 4070 8GB',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 2.55,
      batteryWh: 80,
      generation: 2026,
      screenSize: 16,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'cad', 'premium', 'service_attach'],
    warrantyYears: 3,
    stock: 3,
    condition: 'new',
  }),
  p({
    id: 'cha-xps-14',
    merchantId: 'challenger',
    sku: 'CHA-XPS-14',
    brand: 'Dell',
    model: 'XPS 14',
    title: 'Dell XPS 14 (Core Ultra 7 / RTX 4050 / 32 GB)',
    description: 'Premium thin-and-light with a modest discrete GPU and a 3-year warranty.',
    price: 1999,
    costPrice: 1700,
    specs: {
      cpu: 'Intel Core Ultra 7 155H',
      gpu: 'NVIDIA GeForce RTX 4050 6GB',
      ramGb: 32,
      storageGb: 1000,
      weightKg: 1.68,
      batteryWh: 69,
      generation: 2026,
      screenSize: 14,
      os: 'Windows 11',
      cuda: true,
      dedicatedGpu: true,
      ramUpgradeable: false,
    },
    tags: ['premium', 'portable', 'creator', 'service_attach'],
    warrantyYears: 3,
    stock: 3,
    condition: 'new',
  }),
  p({
    id: 'cha-galaxy-book4',
    merchantId: 'challenger',
    sku: 'CHA-GALAXY-BOOK4',
    brand: 'Samsung',
    model: 'Galaxy Book4 Pro 14',
    title: 'Samsung Galaxy Book4 Pro 14 (Core Ultra 7 / 16 GB)',
    description: 'Lightest machine in the demo catalogue at 1.17 kg. Integrated graphics, excellent for carrying daily.',
    price: 1499,
    costPrice: 1270,
    specs: {
      cpu: 'Intel Core Ultra 7 155H',
      gpu: 'Intel Arc Graphics (integrated)',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.17,
      batteryWh: 63,
      generation: 2026,
      screenSize: 14,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: false,
    },
    tags: ['portable', 'battery', 'dev', 'service_attach'],
    warrantyYears: 2,
    stock: 7,
    condition: 'new',
  }),
  p({
    id: 'cha-modern-15',
    merchantId: 'challenger',
    sku: 'CHA-MODERN-15',
    brand: 'MSI',
    model: 'Modern 15',
    title: 'MSI Modern 15 (Core i5 / integrated)',
    description: 'Office machine. Previous generation, small battery, cheap, well stocked.',
    price: 1199,
    costPrice: 1010,
    specs: {
      cpu: 'Intel Core i5-13420H',
      gpu: 'Intel UHD Graphics (integrated)',
      ramGb: 16,
      storageGb: 512,
      weightKg: 1.7,
      batteryWh: 53,
      generation: 2024,
      screenSize: 15.6,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: false,
      ramUpgradeable: true,
    },
    tags: ['budget', 'office', 'last_gen'],
    warrantyYears: 2,
    stock: 9,
    condition: 'new',
  }),
  p({
    id: 'cha-tuf-a16',
    merchantId: 'challenger',
    sku: 'CHA-TUF-A16',
    brand: 'ASUS',
    model: 'TUF Gaming A16',
    title: 'ASUS TUF Gaming A16 (Ryzen 7 / Radeon RX 7700S)',
    description:
      'Strong rasteriser for the money, but the Radeon GPU means no CUDA — it fails any ML requirement outright.',
    price: 1699,
    costPrice: 1440,
    specs: {
      cpu: 'AMD Ryzen 7 8845HS',
      gpu: 'AMD Radeon RX 7700S 8GB',
      ramGb: 16,
      storageGb: 1000,
      weightKg: 2.2,
      batteryWh: 90,
      generation: 2026,
      screenSize: 16,
      os: 'Windows 11',
      cuda: false,
      dedicatedGpu: true,
      ramUpgradeable: true,
    },
    tags: ['gaming', 'amd', 'service_attach'],
    warrantyYears: 2,
    stock: 5,
    condition: 'new',
  }),
]

/** Accessory / bundle catalogue used by merchant agents within their allowance. */
export const SEED_BUNDLES: Record<string, { type: string; description: string; value: number }[]> = {
  'sherpa-computers': [
    { type: 'carry_bag', description: 'Padded 16" laptop backpack', value: 40 },
    { type: 'mouse', description: 'Wired gaming mouse', value: 25 },
  ],
  bizgram: [
    { type: 'mouse', description: 'Wireless productivity mouse', value: 35 },
    { type: 'ssd_upgrade_voucher', description: 'S$45 storage upgrade voucher', value: 45 },
  ],
  challenger: [
    { type: 'service_pack', description: 'On-site setup + data transfer service', value: 90 },
    { type: 'accessory_kit', description: 'Sleeve, wireless mouse and USB-C hub', value: 125 },
    { type: 'delivery_upgrade', description: 'Guaranteed next-day delivery', value: 30 },
  ],
}
